
--SELECT *
--FROM PortfolioProject..COVIDVDEATHS
--ORDER BY 3,4

--SELECT * 
--FROM PortfolioProject..CovidVaccinations5$
--ORDER BY 3,4


--SELECT DATA THAT WE ARE GOING TO BE USING

SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM PortfolioProject..COVIDVDEATHS
ORDER BY 3,4



--LOOKING AT TOTAL CASES VS TOTAL DEATHS
--SHOWS LIKELIHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY

SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)*100 AS DEATHPERCENTAGE
FROM PortfolioProject..COVIDVDEATHS
WHERE LOCATION LIKE '%STATES%'
ORDER BY 1,2





--LOOKING AT TOTAL CASES VS POPULATION
--SHOWS WHAT PERCENTAGE OF POPULATION GOT COVID
SELECT LOCATION, DATE, TOTAL_CASES, population, (TOTAL_CASES/population)*100 AS DEATHPERCENTAGE
FROM PortfolioProject..COVIDVDEATHS
WHERE LOCATION LIKE '%STATES%'
ORDER BY 1,2



--LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION

SELECT LOCATION, population, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT, MAX((TOTAL_CASES/population))*100 AS PercentPoplutionInfected
FROM PortfolioProject..COVIDVDEATHS
--WHERE LOCATION LIKE '%STATES%'
GROUP BY LOCATION, population
ORDER BY 1,2 


--showing countries with highest death count per populqation
SELECT LOCATION, MAX(cast(total_deaths as int)) AS TotalDeathCount
FROM PortfolioProject..COVIDVDEATHS
--WHERE LOCATION LIKE '%STATES%'
where continent is null
GROUP BY LOCATION
ORDER BY TotalDeathCount desc



--LET'S BREAK THINGS DOWN BY CONTINENT

SELECT continent, MAX(cast(total_deaths as int)) AS TotalDeathCount
FROM PortfolioProject..COVIDVDEATHS
--WHERE LOCATION LIKE '%STATES%'
where continent is not null
GROUP BY continent
ORDER BY TotalDeathCount desc


--SHOWING CONTINTENT WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT continent, MAX(cast(total_deaths as int)) AS TotalDeathCount
FROM PortfolioProject..COVIDVDEATHS
--WHERE LOCATION LIKE '%STATES%'
where continent is not null
GROUP BY continent
ORDER BY TotalDeathCount desc



--GLOBAL NUMBERS

SELECT SUM(NEW_CASES) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATH, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATHPERCENTAGE
FROM PortfolioProject..COVIDVDEATHS
--WHERE LOCATION LIKE '%STATES%'
WHERE continent IS NOT NULL
--GROUP BY DATE
ORDER BY 1,2


--LOOKINT AT TOTAL POPULATION VS VACCINATIONS

SELECT DEA.continent, DEA.location, DEA.DATE, DEA.population, VAC.new_vaccinations
FROM PortfolioProject..COVIDVDEATHS DEA
JOIN PortfolioProject..CovidVaccinations5$ VAC
   ON DEA.location = VAC.LOCATION
   AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3



SELECT DEA.continent, DEA.location, DEA.DATE, DEA.population, VAC.new_vaccinations,
SUM(CONVERT(INT, VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PortfolioProject..COVIDVDEATHS DEA
JOIN PortfolioProject..CovidVaccinations5$ VAC
   ON DEA.location = VAC.LOCATION
   AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
----ORDER BY 2,3



--USE  CTE


WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINTIONS, RollingPeopleVaccinated)
AS
(
SELECT DEA.continent, DEA.location, DEA.DATE, DEA.population, VAC.new_vaccinations,
SUM(CONVERT(INT, VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PortfolioProject..COVIDVDEATHS DEA
JOIN PortfolioProject..CovidVaccinations5$ VAC
   ON DEA.location = VAC.LOCATION
   AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
--ORDER BY 2,3
)
SELECT *, (RollingPeopleVaccinated/POPULATION)*100
FROM POPVSVAC




--TEMP TABLE

DROP TABLE IF EXISTS #PercentPopulationVaccinated
CREATE TABLE #PercentPopulationVaccinated
(
continet nvarchar(255),
location nvarchar(255),
date datetime,
population numeric,
new_vaccinations numeric,
RollingPeopleVaccinated numeric
)
INSERT INTO #PercentPopulationVaccinated
SELECT DEA.continent, DEA.location, DEA.DATE, DEA.population, VAC.new_vaccinations,
SUM(CONVERT(INT, VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PortfolioProject..COVIDVDEATHS DEA
JOIN PortfolioProject..CovidVaccinations5$ VAC
   ON DEA.location = VAC.LOCATION
   AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
----ORDER BY 2,3
SELECT *, (RollingPeopleVaccinated/POPULATION)*100
FROM #PercentPopulationVaccinated




--CREATING VIEW TO STORE DATA FOR LATER VISUALIZATIONS

CREATE VIEW PercentPopulationVaccinated AS
SELECT DEA.continent, DEA.location, DEA.DATE, DEA.population, VAC.new_vaccinations,
SUM(CONVERT(INT, VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PortfolioProject..COVIDVDEATHS DEA
JOIN PortfolioProject..CovidVaccinations5$ VAC
   ON DEA.location = VAC.LOCATION
   AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
--ORDER BY 2,3


SELECT * 
FROM PercentPopulationVaccinated
